
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-comparison-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-comparison-api
  template:
    metadata:
      labels:
        app: email-comparison-api
    spec:
      containers:
      - name: email-comparison-api
        image: YOUR_ACR_NAME.azurecr.io/email-comparison-api:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: email-comparison-service
  namespace: default
spec:
  selector:
    app: email-comparison-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
